# Default values for bahw-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: theunixmaster/bahw
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
service:
  name: http
  type: ClusterIP
  externalPort: 8067
  internalPort: 8367
resources:
  limits:
    cpu: 100m
      
