apiVersion: v1
kind: Service
metadata:
  name: bahw-app-svc
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31225
      port: 8067
      protocol: TCP
      targetPort: 4567
  selector:
    app.kubernetes.io/name: bahw-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}