apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-transform-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
            cj2job: tt-cron
        spec:
          containers:
            - name: test-transform-cronjob
              image: perl:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - for i in {1..10}; do curl -v -R http://bahw-app-svc:8067/?transform=`perl -e 'print["-",0..9,A..K,l..z]->[rand 38]for 1..34'`; echo -e "\n";  done
          restartPolicy: OnFailure